name: Publish (Dokka)

on:
  workflow_call:
    inputs:
      live-run:
        description: Live-run
        type: boolean
        required: true
      branch:
        description: Target branch
        type: string
        required: false
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_doc_and_deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26
          add-to-path: false
          link-to-sdk: true

      - name: Build doc
        run: gradle dokkaHtml

      - name: Deploy doc
        if: ${{ inputs.live-run || false }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./zenoh-kotlin/build/dokka/html
