name: Publish (Dokka)

on:
  workflow_call:
    inputs:
      live-run:
        description: Live-run
        type: boolean
        required: true
      branch:
        description: Target branch
        type: string
        required: false
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_doc_and_deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Build doc
        run: ./gradlew dokkaGenerate

      - name: Deploy doc
        if: ${{ inputs.live-run || false }}
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./zenoh-kotlin/build/dokka/html
